### ISSUE TITLE
MaxMindDBEnv accepts more than two arguments

### ISSUE THREAD

**Issue by bombadil** [maxmind/mod_maxminddb#36]
Right now the directive `MaxMindDBEnv` is implemented using `AP_INIT_ITERATE2` and not using ` AP_INIT_TAKE2`. This means if the directive is specified with more than two parameters, the provided function `set_maxminddb_env` will get called multiple times.

Is this intended? What is the intended behavior? At least the documentation doesn't say anything about `MaxMindDBEnv` taking more than two parameters...

**Comment by bombadil** [comment]
See also the Apache documentation about `ITERATE2` here:
https://ci.apache.org/projects/httpd/trunk/doxygen/group__APACHE__CORE__CONFIG.html#ga07442bbd6a047ee13383f52b9670b026

**Comment by rafl** [comment]
Hello again, Micha :-)

I think you're right on in that the current behaviour almost certainly isn't intentional.

I've tried to figure out what the current behaviour would be when repeating the second argument, and it seems like the very last value would always override any previous ones. That doesn't seem very useful at all!

Should we get rid of it?

**Comment by bombadil** [comment]
Hi Florian,

yes, I would suggest to use `AP_INIT_TAKE2` instead. This should be trivial to implement.

Cheers,
Micha

**Comment by bombadil** [comment]
This seems to be adressed by commit 161b398.

**Comment by oschwald** [comment]
@rafl, any reason not to merge #37?

**Comment by oschwald** [comment]
Fixed by #37.
