### ISSUE TITLE
GEOIP-ADDR support?

### ISSUE THREAD

**Issue by jennyfountain** [maxmind/mod_maxminddb#40]
We use legacy and would like to upgrade.  However, it doesn't appear (maybe I am missing it though) that the new version doesn't support geoip-addr?  Our code uses geoip-addr variable.  

Thanks

**Comment by autarch** [comment]
This module does provide a `MMDB_ADDR` environment variable. Does that no do what  you want? See http://maxmind.github.io/mod_maxminddb/ for details.

Cheers,

Dave Rolsky
MaxMind
Software Engineering Team Lead

**Comment by jennyfountain** [comment]
Hi Dave,
Thanks for responding.  No, unfortunately, our code is referencing env[GEOIP*] so that will not help.  

Thanks!

**Comment by autarch** [comment]
Ah, I see. The environment variables provided by this Apache module are different since it's using entirely new code and databases. In theory, I think you could even run both this and the old mod_geoip2 module in the same process. In order to switch you'd need to update your code.

Cheers,

Dave Rolsky
MaxMind
Software Engineering Team Lead

**Comment by jonahharris** [comment]
Fix in #41
