### ISSUE TITLE
OHS Compatibility

### ISSUE THREAD

**Issue by theiamdude** [maxmind/mod_maxminddb#68]
I am trying to use this module with OHS (Oracle HTTP Server) which is based on Apache 2.4.

Is there any plan to provide the so file required to load the module in OHS? Or is there a way to generate an so file that I can use for the OHS install?

**Comment by nchelluri** [comment]
Hi,

You can generate a `.so` file in `src/.libs` by downloading a [release](https://github.com/maxmind/mod_maxminddb/releases/download/1.1.0/mod_maxminddb-1.1.0.tar.gz) and running `./configure` and `make` (instead of `make install`) in the directory where you extract the archive. These instructions were adapted from https://github.com/maxmind/mod_maxminddb#from-a-named-release-tarball-recommended .

**Comment by theiamdude** [comment]
Thanks for that @nchelluri!! I will give that a go and let you know :)

**Comment by oschwald** [comment]
Closing as this seems to have stalled.
